name: "CodeSee analysis"
description: "Analyze the repo with CodeSee"

# Composite actions cannot access secrets, so we need users to provide the value
# of the CODESEE_ARCH_DIAG_API_TOKEN secret through the codesee-token variable.
# This usually look like this:
# codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
inputs:
  codesee-token:
    description: "The value of CODESEE_ARCH_DIAG_API_TOKEN"
    required: true
  codesee-url:
    description: "The URL to Codesee service"
    required: false
  skip-installing-node:
    description: "Should action skip installing Node?"
    required: false
    type: boolean
    default: false
  skip-installing-jdk:
    description: "Should action skip installing JDK?"
    required: false
    type: boolean
    default: false
  skip-installing-rust:
    description: "Should action skip installing Rust?"
    required: false
    type: boolean
    default: false
  skip-installing-python:
    description: "Should action skip installing Python?"
    required: false
    type: boolean
    default: false
  skip-installing-dotnet:
    description: "Should action skip installing .NET?"
    required: false
    type: boolean
    default: false

runs:
  using: "composite"
  steps:
    - name: Check out the code
      uses: actions/checkout@v3
      id: checkout
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 0

    - name: Configure Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: "18"
      if: ${{ !inputs.skip-installing-node }}

    - name: Detect Languages
      id: detect-languages
      run: node ${{ github.action_path }}/detect-lang/dist/index.js
      shell: bash

    - name: Configure JDK 16
      uses: actions/setup-java@v3
      if: ${{ fromJSON(steps.detect-languages.outputs.languages).java }}
      with:
        java-version: "16"
        distribution: "zulu"
      if: ${{ !inputs.skip-installing-jdk }}

      # CodeSee Maps Go support uses a static binary so there's no setup step required.

    - name: Configure Python 3.x
      uses: actions/setup-python@v4
      if: ${{ fromJSON(steps.detect-languages.outputs.languages).python }}
      with:
        python-version: "3.x"
        architecture: "x64"
      if: ${{ !inputs.skip-installing-python }}

    # We need the rust toolchain because it uses rustc and cargo to inspect the package
    - name: Configure Rust 1.x stable
      uses: dtolnay/rust-toolchain@stable
      if: ${{ fromJSON(steps.detect-languages.outputs.languages).rust }}
      if: ${{ !inputs.skip-installing-rust }}

    - name: Configure .NET SDK 7
      uses: actions/setup-dotnet@v3
      if: ${{ fromJSON(steps.detect-languages.outputs.languages).dot-net }}
      with:
        dotnet-version: "7.x"
        dotnet-quality: "ga"
      if: ${{ !inputs.skip-installing-dotnet }}

    - name: Generate Map
      id: generate-map
      run: node ${{ github.action_path }}/map/dist/index.js
      shell: bash
      env:
        step: map
        api_token: ${{ inputs.codesee-token }}
        github_ref: ${{ github.ref }}
        languages: ${{ steps.detect-languages.outputs.languages }}
        codesee_url: ${{ inputs.codesee-url }}
        NODE_OPTIONS: --max-old-space-size=6144

    - name: Upload Map
      id: upload-map
      run: node ${{ github.action_path }}/map/dist/index.js
      shell: bash
      env:
        step: mapUpload
        api_token: ${{ inputs.codesee-token }}
        github_ref: ${{ github.ref }}
        codesee_url: ${{ inputs.codesee-url }}
        NODE_OPTIONS: --max-old-space-size=6144

    - name: Insights
      id: insights
      run: node ${{ github.action_path }}/map/dist/index.js
      shell: bash
      env:
        step: insights
        api_token: ${{ inputs.codesee-token }}
        github_ref: ${{ github.ref }}
        codesee_url: ${{ inputs.codesee-url }}
        NODE_OPTIONS: --max-old-space-size=6144
