name: "CodeSee analysis"
description: "Analyze the repo with CodeSee"

# Composite actions cannot access secrets, so we need users to provide the value
# of the CODESEE_ARCH_DIAG_API_TOKEN secret through the codesee-token variable.
# This usually look like this:
# codesee-token: ${{ secrets.CODESEE_ARCH_DIAG_API_TOKEN }}
inputs:
  codesee-token:
    description: "The value of CODESEE_ARCH_DIAG_API_TOKEN"
    required: true
  codesee-url:
    description: "The URL to Codesee service"
    required: false
  lang-setup:
    description: "Which language toolchains should we install? Accepted values: 'all', 'none', or a comma separated list of languages: 'node, python, jdk, .net, rust'"
    required: false
    default: "all"

runs:
  using: "composite"
  steps:
    - name: CodeSee No-Op
      shell: bash
      run: echo "CodeSee no longer needs the action to run"
